Repository AY2324S1-CS2103T-W10-2/tp, pull requests merged in 2023-10, with the labels that each got.

#30 Update AboutUs page and side-wide settings
  docs/AboutUs.md
  docs/_markbind/layouts/default.md
  docs/images/SeplendidLogo.png
  docs/images/lamchenghou.png
  docs/site.json
Labels: priority.High

#35 Update User Guide for general sections and mapping commands
  docs/UserGuide.md
  docs/images/MappingListUi.png
  docs/index.md
  docs/site.json
  docs/stylesheets/userguide.css
Labels: priority.High

#32 Edit README.md and Ui.png
  README.md
  docs/images/Ui.png
Labels: priority.High

#33 Update AboutUs.md
  docs/AboutUs.md
  docs/images/alyssaong.png
  docs/team/alyssaong.md
Labels: priority.High

#34 Update AboutUs.md and add Project Portfolio Page (PPP).
  docs/AboutUs.md
  docs/images/dlathyun.png
  docs/team/dlathyun.md
Labels: priority.High

#41 Update Skeletal PPP
  docs/AboutUs.md
  docs/images/alyssaongyx.png
  docs/team/alyssaongyx.md
Labels: priority.High

#37 Edit AboutUs
  docs/AboutUs.md
Labels: priority.High

#46 Update developers' guide
  docs/DeveloperGuide.md
Labels: priority.High

#47 Edit AboutUs page
  docs/AboutUs.md
  docs/images/aliciamichellew.png
Labels: priority.High

#50 Add PPP
  docs/team/aliciamichellew.md
Labels: priority.High

#51 Update User Stories
  docs/DeveloperGuide.md
Labels: priority.High

#53 Update User Guide
  docs/UserGuide.md
  docs/images/NoteAddUi.png
  docs/images/NoteListUi.png
  docs/images/NoteTagUi.png
  docs/images/NoteUpdateUi.png
Labels: priority.High

#55 Update user stories in developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#56 Add use cases to developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#70 Add Note Feature
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#73 Add university
  src/main/java/seedu/address/model/university/UniqueUniversityList.java
  src/main/java/seedu/address/model/university/University.java
  src/main/java/seedu/address/model/university/UniversityName.java
  src/main/java/seedu/address/model/university/exceptions/UniversityNotFoundException.java
Labels: priority.High

#74 Add PartnerCourse
  src/main/java/seedu/address/model/partnercourse/PartnerCode.java
  src/main/java/seedu/address/model/partnercourse/PartnerCourse.java
  src/main/java/seedu/address/model/partnercourse/PartnerName.java
  src/main/java/seedu/address/model/partnercourse/UniquePartnerCourseList.java
  src/main/java/seedu/address/model/partnercourse/exceptions/DuplicatePartnerCourseException.java
  src/main/java/seedu/address/model/partnercourse/exceptions/PartnerCourseNotFoundException.java
Labels: priority.High

#88 Fix Checkstyle errors and compilation errors
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/PartnerCourseAddCommand.java
  src/main/java/seedu/address/logic/commands/PartnerCourseCommand.java
  src/main/java/seedu/address/logic/commands/UniversityCommand.java
  src/main/java/seedu/address/logic/commands/UniversityListCommand.java
  src/main/java/seedu/address/logic/parser/PartnerCourseAddCommandParser.java
  src/main/java/seedu/address/model/PartnerCourseCatalogue.java
  src/main/java/seedu/address/model/ReadOnlyPartnerCourseCatalogue.java
  src/main/java/seedu/address/model/ReadOnlyUniversityCatalogue.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/SeplendidModel.java
  src/main/java/seedu/address/model/SeplendidModelManager.java
  src/main/java/seedu/address/model/UniversityCatalogue.java
  src/main/java/seedu/address/model/partnercourse/PartnerCode.java
  src/main/java/seedu/address/model/partnercourse/PartnerCourse.java
  src/main/java/seedu/address/model/partnercourse/PartnerName.java
  src/main/java/seedu/address/model/partnercourse/UniquePartnerCourseList.java
  src/main/java/seedu/address/model/partnercourse/exceptions/DuplicatePartnerCourseException.java
  src/main/java/seedu/address/model/partnercourse/exceptions/PartnerCourseNotFoundException.java
  src/main/java/seedu/address/model/university/UniqueUniversityList.java
  src/main/java/seedu/address/model/university/University.java
  src/main/java/seedu/address/model/university/UniversityName.java
  src/main/java/seedu/address/model/university/exceptions/DuplicateUniversityException.java
  src/main/java/seedu/address/model/university/exceptions/UniversityNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPartnerCourse.java
  src/main/java/seedu/address/storage/JsonAdaptedUniversity.java
  src/main/java/seedu/address/storage/JsonPartnerCourseCatalogueStorage.java
  src/main/java/seedu/address/storage/JsonSerializableUniversityCatalogue.java
  src/main/java/seedu/address/storage/PartnerCourseCatalogueStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UniversityCatalogueStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/localcourse/LocalCourseTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High

#105 Add university search
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UniversitySearchCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SeplendidParser.java
  src/main/java/seedu/address/logic/parser/UniversitySearchCommandParser.java
  src/main/java/seedu/address/model/SeplendidModel.java
  src/main/java/seedu/address/model/SeplendidModelManager.java
  src/main/java/seedu/address/model/UniversityCatalogue.java
  src/main/java/seedu/address/model/university/UniversityName.java
  src/main/java/seedu/address/model/university/UniversityNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/LocalCourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/LocalCourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/PartnerCourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/PartnerCourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/UniversitySearchCommandParserTest.java
Labels: priority.High

#113 Update developer guide with implementation details
  docs/DeveloperGuide.md
  docs/diagrams/MappingAddSequenceDiagram.puml
  docs/diagrams/MappingDeleteSequenceDiagram.puml
  docs/diagrams/SeplendidParserActivityDiagram.puml
Labels: priority.Medium

#117 Update User Guide
  docs/UserGuide.md
  docs/images/LocalCourseListUi.png
  docs/images/LocalcourseListUi.png
Labels: priority.High

#115 Add sort command for LocalCourse
  src/main/java/seedu/address/logic/SeplendidLogic.java
  src/main/java/seedu/address/logic/SeplendidLogicManager.java
  src/main/java/seedu/address/logic/commands/LocalCourseSortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LocalCourseAddCommandParser.java
  src/main/java/seedu/address/logic/parser/LocalCourseSortCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SeplendidParser.java
  src/main/java/seedu/address/model/SeplendidModel.java
  src/main/java/seedu/address/model/SeplendidModelManager.java
  src/main/java/seedu/address/model/UniversityCatalogue.java
  src/main/java/seedu/address/model/localcourse/LocalCourseAttribute.java
  src/main/java/seedu/address/model/localcourse/comparator/LocalCourseComparatorByLocalCode.java
  src/main/java/seedu/address/model/localcourse/comparator/LocalCourseComparatorByLocalName.java
  src/main/java/seedu/address/model/partnercourse/PartnerCourse.java
  src/main/java/seedu/address/seplendidui/MainWindow.java
  src/main/java/seedu/address/seplendidui/UiUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedUniversity.java
  src/main/java/seedu/address/storage/JsonSerializableUniversityCatalogue.java
  src/main/java/seedu/address/storage/UniversityCatalogueStorage.java
  src/test/data/JsonPartnerCourseCatalogueStorageTest/invalidAndValidPartnerCourseCatalogue.json
  src/test/data/JsonPartnerCourseCatalogueStorageTest/invalidPartnerCourseCatalogue.json
  src/test/data/JsonPartnerCourseCatalogueStorageTest/notJsonFormatPartnerCourseCatalogue.json
  src/test/data/JsonSerializableLocalCourseCatalogueTest/typicalLocalCourseCatalogue.json
  src/test/data/JsonSerializablePartnerCourseCatalogueTest/duplicatePartnerCourseInCatalogue.json
  src/test/data/JsonSerializablePartnerCourseCatalogueTest/invalidPartnerCourseInCatalogue.json
  src/test/data/JsonSerializablePartnerCourseCatalogueTest/typicalPartnerCourseCatalogue.json
  src/test/data/JsonSerializableUniversityCatalogueTest/duplicateUniversityInCatalogue.json
  src/test/data/JsonSerializableUniversityCatalogueTest/invalidUniversityInCatalogue.json
  src/test/data/JsonSerializableUniversityCatalogueTest/typicalUniversityCatalogue.json
  src/test/data/JsonUniversityCatalogueStorageTest/invalidAndValidUniversityCatalogue.json
  src/test/data/JsonUniversityCatalogueStorageTest/invalidUniversityCatalogue.json
  src/test/data/JsonUniversityCatalogueStorageTest/notJsonFormatUniversityCatalogue.json
  src/test/java/seedu/address/logic/SeplendidLogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LocalCourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/LocalCourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/LocalCourseSortCommandTest.java
  src/test/java/seedu/address/logic/commands/PartnerCourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/PartnerCourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/LocalCourseSortCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SeplendidParserTest.java
  src/test/java/seedu/address/model/UniversityCatalogueTest.java
  src/test/java/seedu/address/model/localcourse/LocalCourseAttributeTest.java
  src/test/java/seedu/address/model/localcourse/comparator/LocalCourseComparatorByLocalCodeTest.java
  src/test/java/seedu/address/model/localcourse/comparator/LocalCourseComparatorByLocalNameTest.java
  src/test/java/seedu/address/model/partnercourse/PartnerCourseTest.java
  src/test/java/seedu/address/model/partnercourse/UniquePartnerCourseListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUniversityTest.java
  src/test/java/seedu/address/storage/JsonLocalCourseCatalogueStorageTest.java
  src/test/java/seedu/address/storage/JsonPartnerCourseCatalogueTest.java
  src/test/java/seedu/address/storage/JsonSerializableLocalCourseCatalogueTest.java
  src/test/java/seedu/address/storage/JsonSerializablePartnerCourseCatalogueTest.java
  src/test/java/seedu/address/storage/JsonSerializableUniversityCatalogueTest.java
  src/test/java/seedu/address/storage/JsonUniversityCatalogueStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/LocalCourseUtil.java
  src/test/java/seedu/address/testutil/PartnerCourseBuilder.java
  src/test/java/seedu/address/testutil/PartnerCourseUtil.java
  src/test/java/seedu/address/testutil/TypicalObjects.java
Labels: priority.High

#144 Add `search` by tags feature for Note
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/NoteSearchCommand.java
  src/main/java/seedu/address/logic/parser/NoteSearchCommandParser.java
  src/main/java/seedu/address/logic/parser/SeplendidParser.java
  src/main/java/seedu/address/model/SeplendidModel.java
  src/main/java/seedu/address/model/SeplendidModelManager.java
  src/main/java/seedu/address/model/notes/NoteTagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/LocalCourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/LocalCourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/PartnerCourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/PartnerCourseDeleteCommandTest.java
Labels: priority.High

#149 Forking workflow for v1.1
  temp.txt
Labels: priority.Low
